In [1]:
import numpy as np

In [2]:
# standard python list
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
# unsaved np array
# 1-dimensional vector
np.array(mylist)

array([1, 2, 3])

In [5]:
# the python list is unchanged because it
# wasn't saved into a variable
mylist

[1, 2, 3]

In [6]:
# save the np array
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
# python list of lists
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# convert the list of lists into a 2-dimensional
# matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# numpy's `arange()` is very similar to
# python's `range()`
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
# if 1D, pass in an int
# default datatype is float
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
# if 2D, pass in a tuple of ints
# rows first, then columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# specify to return ints instead of 
# default float
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# return evenly spaced numbers over a 
# specified interval
# NOT THE SAME AS np.arange()

# takes a start, stop, and number of spaces in between
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,80,11)

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80.])

In [27]:
# returns the same number as the num (third) 
# param
len(np.linspace(0,80,11))

11