### NYC Taxi-Airport Data

In [1]:
# import modules
import csv
import numpy as np

In [2]:
# import nyc_taxis.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

In [3]:
# remove the header row
taxi_list = taxi_list[1:]

In [4]:
# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

1. Add a line of code using the `numpy.array()` constructor to convert the `converted_taxi_list` variable to a NumPy ndarray.
2. Assign the result to the variable name `taxi`.

In [5]:
taxi = np.array(converted_taxi_list)

### Array Shapes

In [6]:
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


1. Assign the shape of `taxi` to `taxi_shape`. Print the result

In [7]:
taxi_shape = taxi.shape

In [8]:
print(taxi_shape)

(89560, 15)


### Selecting and Slicing Rows and Items from ndarrays

1. Select the row at index `0`. Assign it to `row_0`.
2. Select every column for the rows at indexes `391` to `500` inclusive. Assign them to `rows_391_to_500`.
3. Select the item at row index `21` and column index `5`. Assign it to `row_21_column_5`.

In [9]:
row_0 = taxi[0]
rows_391_to_500 = taxi[391:501]
row_21_column_5 = taxi[21,5]

### Selecting Columns and Custom Slicing ndarrays

From the `taxi` ndarray:
1. Select every row for the columns at indexes `1`, `4`, and `7`. Assign them to `columns_1_4_7`.
2. Select the columns at indexes `5` to `8` inclusive for the row at index `99`. Assign them to `row_99_columns_5_to_8`.
3. Select the rows at indexes `100` to `200` inclusive for the column at index `14`. Assign them to `rows_100_to_200_column_14`.

In [10]:
cols = [1, 4, 7]
columns_1_4_7 = taxi[:, cols]

row_99_columns_5_to_8 = taxi[99, 5:9]

rows_100_to_200_column_14 = taxi[100:201, 14]

### Vector Math

1. Use vector addition to add `fare_amount` and `fees_amount`. Assign the result to `fares_and_fees`.

In [11]:
fare_amount = taxi[:, 9]
fees_amount = taxi[:, 10]

fares_and_fees = fare_amount + fees_amount

In [14]:
trip_distance_miles = taxi[:,7]
trip_length_seconds = taxi[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

1. Use vector division to divide `trip_distance_miles` by `trip_length_hours`. Assign the result to `trip_mph`.

In [15]:
trip_mph = trip_distance_miles / trip_length_hours

### Calculating Statistics for 1D ndarrays

[NumPy ndarray calculation](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.ndarray.html#calculation)
- `ndarray.min()` to calculate the minimum value
- `ndarray.max()` to calculate the maximum value
- `ndarray.mean()` to calculate the mean or average values
- `ndarray.sum()` to calculate the sum of values

In [16]:
mph_min = trip_mph.min()

1. Use the `ndarray.max()` method to calculate the maximum value of `trip_mph`. Assign the result to `mph_max`.
2. Use the `ndarray.mean()` method to calculate the average value of `trip_mph`. Assign the result to `mph_mean`.

In [17]:
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

### Calculating Statistics for 2D ndarrays

In [18]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]
# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]

We've already assigned the first five rows of `taxi` to `taxi_first_five` and the first four columns in the table above to `fare_components`.

Check that the sum of each row in `fare_components` equals the value in the `total_amount` column.

1. Use the `ndarray.sum()` method to calculate the sum of each row in `fare_components`. Assign the result to `fare_sums`.
2. Extract the 14th column in `taxi_first_five`. Assign to `fare_totals`.
3. Print `fare_totals` and `are_sums`.

In [19]:
fare_sums = fare_components.sum(axis=1)
fare_totals = taxi_first_five[:, 13]
print(fare_totals)
print(fare_sums)

[69.99 54.3  37.8  32.76 18.8 ]
[69.99 54.3  37.8  32.76 18.8 ]
